config/routes.rb
Rails.application.routes.draw do
  get 'posts' => 'posts#index'
  resources :posts
  resources :comments
  get 'sessions/new'
  resources :users do
    resources :posts do 
    end
  end
  get '/' => 'welcome#index'
  get '/signup' => 'users#new'
  root 'welcome#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new

    end

    def create
        @comment = Comment.create(comment_params)
        @comment.save
        redirect_to user_post_path(@comment.user_id, @comment.post_id)
    end

    def destroy
      @comment = Comment.find(params[:id])
      @p = [@comment.user_id, @comment.post_id]
      @comment.destroy
      redirect_to user_post_path(@p[0],@p[1])
    end
end

private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(post_id: @post.id)
    puts "**********************"
    puts @comments
    puts "**********************"
  end

  def new
    @post = Post.new
    @id = current_user.id
  end

  def create
    Post.create(post_params)
    redirect_to user_path(current_user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(update_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end

  private

  def update_params
    params.require(:post).permit(:title, :content)
  end


  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.password == params[:session][:password]
      log_in @user
      redirect_to user_path @user.id
    else
      
    
    end
  end

  def destroy
    log_out
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    User.create(user_params)
    redirect_to '/login'
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  def name
    
  end

  def destroy
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
    @posts.each(& :destroy)
    @user.destroy
    @current_user = nil
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:uname, :fname, :lname, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all
    @posts = Post.all
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    #login
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
       @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session[:user_id] = nil
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse ">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">RailsBlog</a>
      </div>
  <ul class="nav navbar-nav layoutnav">
    <li><a href="/">Home</a></li>
    <%if logged_in? %>
      <li><a href="/users">Users</a></li>
      <li><a href="/users/<%=current_user.id%>">Profile</a></li>
      <li><%= link_to "Log Out", logout_path, method: "delete"%></li>
      <li><a href="/posts">Posts</a></li>
    <%else%>
      <li><a href="/signup">Create Account</a></li>
      <li><a href="/login">Login</a></li>
    <%end%>
  </ul>
    <ul class="nav navbar-nav navbar-right">
      <%if current_user == nil%><li>Not logged in</li><%else%><p>Logged in as: <%=current_user.fname%></p><%end%>
    </ul>
    </div>
   </nav>
    <%= yield %>
    
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= form_for @post do |f|  %>

    <div>
        <%= f.label "Title" %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label "Content" %>
        <%= f.text_field :content %>
    </div>

    <div>
        <%= f.submit 'Submit' %>
    </div>

<% end %>

app/views/posts/index.html.erb
<div class="container">
<h1>Posts</h1>
    
        <% @posts.reverse.each do |post| %>
            <%@user = User.find(post.user_id) %>
            <div class="post">
                <h3>By: <%=link_to @user.fname, user_path(@user.id)%></h3>
                <% if current_user  == @user %>
                    <p><%= link_to 'Delete', post, :method => :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger' %> </p>
                <% else %>
            <% end %>
            <h3> <%=link_to post.title, user_post_path(@user.id, post.id)%></h3>
            <p><%=post.content%></p>
            </div>
        <% end %>
    
</div>

app/views/posts/new.html.erb
<div class="container post">
<%= form_for @post, url: user_posts_path(current_user) do |f|  %>


    <div>
        <%= f.label "Title" %>
        <%= f.text_field :title, :maxlength => 15 %>
    </div>

    <div>
        <%= f.label "Content" %>
        <%= f.text_area :content, :class => 'form-control ', :maxlength => 300 %>
    </div>

    <div>
        <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>


    <div>
        <%= f.submit 'Submit', :class => 'btn btn-primary' %>
    </div>

<% end %>
</div>

app/views/posts/show.html.erb
<h1>View Post</h1>

<h2><%= @post.title %></h2>
<p><%= @post.content %></h1>

<%= form_for @comment do |f|  %>

    <div>
        <%= f.label "Comment" %>
        <%= f.text_field :content %>
    </div>

    <div>
        <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>

    <div>
        <%= f.hidden_field :post_id, :value => @post.id%>
    </div>

    <div>
        <%= f.submit 'Submit' %>
    </div>

<% end %>

<h1>Comments</h1>
    <% @comments.each do |f| %>
        <% @commentuser = User.find(f.user_id) %>
        <h4>By: <%=@commentuser.fname  %></h4><% if @current_user == @commentuser %><h4> <%= link_to 'Delete', f, :method => :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger' %></h4><% else %><% end %> <p><%= f.content %></p>
    <% end %>

app/views/users/edit.html.erb
<div class="container login">
<h1>Edit Account</h1>

<%= form_for @user do |f| %>

    <div>
        <%= f.label "First Name" %>
        <%= f.text_field :fname %>
    </div>

    <div>
        <%= f.label "Last Name" %>
        <%= f.text_field :lname %>
    </div>

    <div>
        <%= f.label :username %>
        <%= f.text_field :uname %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>

    <div>
        <%= f.submit 'Edit Account', :class => 'btn btn-primary' %>
    </div>

<% end %>

</div>

app/views/users/index.html.erb
<div class="container">
    <h1>Users</h1>


    <% @users.each do |user| %>
        <div class="post" >
            <h2><%= link_to(user.fname + " " + user.lname, user_path(user) ) %></h2>
            <h4>Username: <%=user.uname%></h4>
            <h4>Email: <%=user.email%></h4>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1>Create An Account</h1>

<%= form_for @user do |f| %>

    <div>
        <%= f.label "First Name" %>
        <%= f.text_field :fname %>
    </div>

    <div>
        <%= f.label "Last Name" %>
        <%= f.text_field :lname %>
    </div>

    <div>
        <%= f.label :username %>
        <%= f.text_field :uname %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>

    <div>
        <%= f.submit 'Create Account' %>
    </div>

<% end %>

app/views/users/show.html.erb
<div class="container">
<h1><%=@user.fname%> <%=@user.lname%>'s profile</h1><br>

<% if current_user == @user %><%= link_to "Create new post", new_user_post_path(current_user.id), :class => 'btn btn-primary' %> <% else %><% end %>

<% if current_user == @user %> <%= link_to "Edit Account", edit_user_path(current_user.id), :class => 'btn btn-primary'  %><% else %><% end %>

<% if current_user == @user %> <%= link_to "Delete Account", @user, :method => :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger'  %><% else %><% end %>


<% @posts.reverse.each do |post| %>
    <div class="post">
    <h3>
    <%=post.id  %> <%=link_to post.title, user_post_path(@user.id, post.id)  %>
    </h3>
     <% if current_user == @user %>
      <%= link_to 'Edit',  edit_user_post_path(current_user, post.id), :class => 'btn btn-primary'%>
      <%= link_to 'Delete', post, :method => :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger' %>
    <% else %>
    <% end %>
    <p class="post-text"><%=post.content  %></p>
    </div>
<% end %>  
</div>

app/views/welcome/index.html.erb
<div class="container" style="text-align:center;">
<h1>Welcome to the rails blog!</h1>
<img src="/rails.png" style="height:250px; width:500px; margin:100px;">

</div>

s